### PR TITLE
Fix bugs in oriented distance function

### PR DESCRIPTION
**Pull request by jeizenga**
Two bugs in my path-based oriented distance estimation function. One that caused it to needlessly search out to the maximum search distance in every call and another that could seg fault near the end of graphs.

### CODE REVIEW

**Comment by adamnovak** [comment]
Looks like this somehow made some of the graphs fail to verify in the tests.

**Comment by jeizenga** [comment]
@ekg 

This doesn't seem to be a problem with this PR. These tests were also failed in the most recent commit in master: https://travis-ci.org/vgteam/xg/builds/244266590?utm_source=github_status&utm_medium=notification

I did some cursory poking around, and it appears the problem is an out of bounds index in XG::extract_threads.

**Comment by jeizenga** [comment]
Calling the command `xg -Vrdv data/z.vg 2>&1` from the test script with debug flags on:

```
validating threads
Extracting threads
1 threads start at side 2
Extracting thread 0
Assertion failed: (idx < this->size()), function operator[], file /Users/Jordan/Documents/GitHub/vg/include/sdsl/int_vector.hpp, line 1396.
Abort trap: 6
```

**Comment by adamnovak** [comment]
As per @ekg's advice, I'm going to merge this. But we need to look at why our tests are failing.

I think it was a commit by @ekg between https://github.com/vgteam/xg/commit/0d2fa5897b0bb0ff561717de208431054016ba96 and https://github.com/vgteam/xg/commit/90e3b43c58713c77f4a2aeab664ad7228e20c71c9 that broke the build. We should probably figure out which it was and maybe roll it back or fix it.

**Pull request merged**
